### ISSUE TITLE
Set up the Kanban board

### ISSUE THREAD

**Issue by fherrerao** [fherrerao/Capstone-Group-Project#41]
# Hi There 💯 

- I share the link to the project: https://github.com/fherrerao/Capstone-Group-Project/projects/4
- We are two people in the project.

**Comment by medaminedev66** [comment]
# Required Changes ♻️

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Aspects to improve ♻️

- [ ] When I click the URL to see the project in your description, it sends me to the GitHub repository in place of the project, please work on it. 😃 
- [ ] It looks like the tasks are not assigned to anyone on the to-do section, please, make sure the photo appears on each card to be sure it was assigned. Look at the example below:
![image](https://user-images.githubusercontent.com/20563252/132227395-a881beb5-8086-421e-9c20-e0ae87ecb6a4.png)

your project at this point:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/77190203/152042167-0eff5762-64c3-4b73-967f-8d9c0963efb9.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello team, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
